import { OptionLeg } from '@/types';

interface GraphicTemplateProps {
  type: 'apertura' | 'aggiustamento' | 'chiusura';
  data: {
    tag: string;
    date?: string;
    openingDate?: string;
    closingDate?: string;
    daxSpot?: number;
    legs?: OptionLeg[];
    closedLegs?: OptionLeg[];
    addedLegs?: OptionLeg[];
    pnlPoints?: number;
    pnlEuro?: number;
    duration?: number;
  };
}

/**
 * Componente per rendering HTML delle grafiche Telegram
 * Questo HTML viene convertito in PNG usando html-to-image
 */
export function GraphicTemplate({ type, data }: GraphicTemplateProps) {
  const formatDate = (date: string | Date) => {
    const d = typeof date === 'string' ? new Date(date) : date;
    return d.toLocaleDateString('it-IT', { day: '2-digit', month: '2-digit', year: 'numeric' });
  };

  const formatPrice = (price: number) => {
    return price.toLocaleString('it-IT', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  };

  const formatPnL = (value: number) => {
    const sign = value >= 0 ? '+' : '';
    return `${sign}${formatPrice(value)}`;
  };

  if (type === 'apertura') {
    return (
      <div className="graphic-card" style={{
        width: '500px',
        height: '700px',
        background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
        color: 'white',
        padding: '24px',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        position: 'relative',
        overflow: 'hidden'
      }}>
        {/* Header */}
        <div style={{ marginBottom: '16px' }}>
          <div style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '4px' }}>
            🇩🇪 DAX Options Trading
          </div>
          <h1 style={{ fontSize: '24px', fontWeight: 'bold', margin: '0 0 8px 0' }}>
            Nuova Operazione
          </h1>
          <div style={{ fontSize: '14px', color: '#94a3b8' }}>
            {data.tag}
          </div>
        </div>

        {/* Info Box */}
        <div style={{
          background: 'rgba(255, 255, 255, 0.05)',
          borderRadius: '12px',
          padding: '12px',
          marginBottom: '16px',
          border: '1px solid rgba(255, 255, 255, 0.1)',
          fontSize: '12px'
        }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
            <span style={{ color: '#94a3b8' }}>Data Apertura</span>
            <span style={{ fontWeight: '600' }}>{data.date ? formatDate(data.date) : '-'}</span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span style={{ color: '#94a3b8' }}>DAX Spot</span>
            <span style={{ fontWeight: '600', fontSize: '16px', color: '#3b82f6' }}>
              {data.daxSpot ? formatPrice(data.daxSpot) : '-'}
            </span>
          </div>
        </div>

        {/* Legs */}
        <div style={{ marginBottom: '16px' }}>
          <h2 style={{ fontSize: '14px', marginBottom: '8px', color: '#94a3b8' }}>
            Gambe ({data.legs?.length || 0})
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            {data.legs?.map((leg, idx) => (
              <div key={idx} style={{
                background: 'rgba(255, 255, 255, 0.05)',
                borderRadius: '8px',
                padding: '8px',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center',
                fontSize: '11px'
              }}>
                <div>
                  <div style={{ fontWeight: '600', fontSize: '12px', marginBottom: '2px' }}>
                    {leg.quantity > 0 ? 'Long' : 'Short'} {leg.optionType} {formatPrice(leg.strike)}
                  </div>
                  <div style={{ fontSize: '10px', color: '#94a3b8' }}>
                    Qty: {Math.abs(leg.quantity)} • Prezzo: {formatPrice(leg.tradePrice)} • Scad: {formatDate(leg.expiryDate)}
                  </div>
                </div>
                <div style={{
                  background: leg.quantity > 0 ? '#10b981' : '#ef4444',
                  color: 'white',
                  padding: '4px 8px',
                  borderRadius: '6px',
                  fontSize: '10px',
                  fontWeight: '700'
                }}>
                  {leg.quantity > 0 ? 'LONG' : 'SHORT'}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div style={{
          position: 'absolute',
          bottom: '12px',
          left: '24px',
          right: '24px',
          textAlign: 'center',
          color: '#64748b',
          fontSize: '10px'
        }}>
          Generated by Option DAX Trading System
        </div>
      </div>
    );
  }

  if (type === 'aggiustamento') {
    return (
      <div className="graphic-card" style={{
        width: '500px',
        height: '650px',
        background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
        color: 'white',
        padding: '24px',
        fontFamily: 'system-ui, -apple-system, sans-serif',
        position: 'relative',
        overflow: 'hidden'
      }}>
        {/* Header */}
        <div style={{ marginBottom: '16px' }}>
          <div style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '4px' }}>
            🇩🇪 DAX Options Trading
          </div>
          <h1 style={{ fontSize: '24px', fontWeight: 'bold', margin: '0 0 8px 0' }}>
            Aggiustamento
          </h1>
          <div style={{ fontSize: '14px', color: '#94a3b8' }}>
            {data.tag}
          </div>
        </div>

        {/* P&L Box */}
        <div style={{
          background: data.pnlPoints && data.pnlPoints >= 0 
            ? 'rgba(16, 185, 129, 0.1)' 
            : 'rgba(239, 68, 68, 0.1)',
          borderRadius: '12px',
          padding: '12px',
          marginBottom: '16px',
          border: `1px solid ${data.pnlPoints && data.pnlPoints >= 0 ? '#10b981' : '#ef4444'}`
        }}>
          <div style={{ color: '#94a3b8', marginBottom: '4px', fontSize: '12px' }}>P&L Parziale</div>
          <div style={{
            fontSize: '24px',
            fontWeight: 'bold',
            color: data.pnlPoints && data.pnlPoints >= 0 ? '#10b981' : '#ef4444'
          }}>
            {data.pnlEuro ? formatPnL(data.pnlEuro) : '-'} €
          </div>
          <div style={{ fontSize: '12px', color: '#94a3b8', marginTop: '2px' }}>
            {data.pnlPoints ? formatPnL(data.pnlPoints) : '-'} punti
          </div>
        </div>

        {/* Closed Legs */}
        {data.closedLegs && data.closedLegs.length > 0 && (
          <div style={{ marginBottom: '12px' }}>
            <h2 style={{ fontSize: '12px', marginBottom: '6px', color: '#94a3b8' }}>
              Gambe Chiuse ({data.closedLegs.length})
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              {data.closedLegs.map((leg, idx) => (
                <div key={idx} style={{
                  background: 'rgba(239, 68, 68, 0.1)',
                  borderRadius: '8px',
                  padding: '6px',
                  border: '1px solid rgba(239, 68, 68, 0.3)',
                  fontSize: '11px'
                }}>
                  <div style={{ fontWeight: '600', marginBottom: '2px' }}>
                    {leg.quantity > 0 ? 'Long' : 'Short'} {leg.optionType} {formatPrice(leg.strike)}
                  </div>
                  <div style={{ fontSize: '10px', color: '#94a3b8' }}>
                    Qty: {Math.abs(leg.quantity)} • Prezzo: {formatPrice(leg.tradePrice)} • Scad: {formatDate(leg.expiryDate)}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Added Legs */}
        {data.addedLegs && data.addedLegs.length > 0 && (
          <div style={{ marginBottom: '12px' }}>
            <h2 style={{ fontSize: '12px', marginBottom: '6px', color: '#94a3b8' }}>
              Gambe Aggiunte ({data.addedLegs.length})
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              {data.addedLegs.map((leg, idx) => (
                <div key={idx} style={{
                  background: 'rgba(16, 185, 129, 0.1)',
                  borderRadius: '8px',
                  padding: '6px',
                  border: '1px solid rgba(16, 185, 129, 0.3)',
                  fontSize: '11px'
                }}>
                  <div style={{ fontWeight: '600', marginBottom: '2px' }}>
                    {leg.quantity > 0 ? 'Long' : 'Short'} {leg.optionType} {formatPrice(leg.strike)}
                  </div>
                  <div style={{ fontSize: '10px', color: '#94a3b8' }}>
                    Qty: {Math.abs(leg.quantity)} • Prezzo: {formatPrice(leg.tradePrice)} • Scad: {formatDate(leg.expiryDate)}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Footer */}
        <div style={{
          position: 'absolute',
          bottom: '12px',
          left: '24px',
          right: '24px',
          textAlign: 'center',
          color: '#64748b',
          fontSize: '10px'
        }}>
          Generated by Option DAX Trading System
        </div>
      </div>
    );
  }

  // Chiusura
  return (
    <div className="graphic-card" style={{
      width: '500px',
      height: '600px',
      background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
      color: 'white',
      padding: '24px',
      fontFamily: 'system-ui, -apple-system, sans-serif',
      position: 'relative',
      overflow: 'hidden',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center'
    }}>
      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: '24px' }}>
        <div style={{ fontSize: '12px', color: '#94a3b8', marginBottom: '4px' }}>
          🇩🇪 DAX Options Trading
        </div>
        <h1 style={{ fontSize: '28px', fontWeight: 'bold', margin: '0 0 8px 0' }}>
          Chiusura Totale
        </h1>
        <div style={{ fontSize: '16px', color: '#94a3b8' }}>
          {data.tag}
        </div>
      </div>

      {/* P&L Result */}
      <div style={{
        background: data.pnlPoints && data.pnlPoints >= 0 
          ? 'rgba(16, 185, 129, 0.1)' 
          : 'rgba(239, 68, 68, 0.1)',
        borderRadius: '16px',
        padding: '24px',
        marginBottom: '24px',
        border: `2px solid ${data.pnlPoints && data.pnlPoints >= 0 ? '#10b981' : '#ef4444'}`,
        textAlign: 'center',
        minWidth: '300px'
      }}>
        <div style={{ color: '#94a3b8', marginBottom: '8px', fontSize: '14px' }}>
          Risultato Finale
        </div>
        <div style={{
          fontSize: '36px',
          fontWeight: 'bold',
          color: data.pnlPoints && data.pnlPoints >= 0 ? '#10b981' : '#ef4444',
          marginBottom: '4px'
        }}>
          {data.pnlEuro ? formatPnL(data.pnlEuro) : '-'} €
        </div>
        <div style={{ fontSize: '14px', color: '#94a3b8' }}>
          {data.pnlPoints ? formatPnL(data.pnlPoints) : '-'} punti
        </div>
      </div>

      {/* Info */}
      <div style={{
        background: 'rgba(255, 255, 255, 0.05)',
        borderRadius: '12px',
        padding: '16px',
        border: '1px solid rgba(255, 255, 255, 0.1)',
        minWidth: '300px',
        fontSize: '12px'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
          <span style={{ color: '#94a3b8' }}>Data Apertura</span>
          <span style={{ fontWeight: '600' }}>
            {data.openingDate ? formatDate(data.openingDate) : '-'}
          </span>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
          <span style={{ color: '#94a3b8' }}>Data Chiusura</span>
          <span style={{ fontWeight: '600' }}>
            {data.closingDate ? formatDate(data.closingDate) : '-'}
          </span>
        </div>
        <div style={{ display: 'flex', justifyContent: 'space-between' }}>
          <span style={{ color: '#94a3b8' }}>Durata</span>
          <span style={{ fontWeight: '600' }}>
            {data.duration ? `${data.duration} giorni` : '-'}
          </span>
        </div>
      </div>

      {/* Footer */}
      <div style={{
        position: 'absolute',
        bottom: '12px',
        left: '24px',
        right: '24px',
        textAlign: 'center',
        color: '#64748b',
        fontSize: '10px'
      }}>
        Generated by Option DAX Trading System
      </div>
    </div>
  );
}
